// Generated by https://quicktype.io

export interface Schema {
  data: Datum[]
  links: Links
  meta: Meta
}

export interface Variant {
  id: number
  sku: null
  created_at: string
  updated_at: string
  barcode: null
  type: string
  grams: number | null
  title: string
  pricing_type: string
  price: Price
  price_unit_exc_vat: null
  inventory_policy: null
  inventory_items: any[]
  vat_id: number
  product: Datum
  subscription_plans: any[]
  variant_type_options: any[]
  media: Media[]
}

export interface Datum {
  id: number
  title: string
  slug: string
  sku: null
  description: string
  custom_fields: any[]
  expiry: null
  product_class?: Brand
  product_type: string
  meta_title: null
  meta_keywords: null
  meta_description: null
  created_at: string
  updated_at: string
  deleted_at: null
  featured: boolean
  brand?: Brand
  media: Media[]
  taxonomies: Taxonomies
  variants?: Variant[]
  groupables?: any[]
  meta_fields: MetaField[]
  meta_media: any[]
}

export interface Media {
  uuid: string
  name: string
  file_name: string
  url: string
  order: number
  custom_properties: any[]
  type: string
  extension: string
  size: number
  mime_type: string
  responsive_images: ResponsiveImages
  conversions: Conversions
}

export interface Conversions {
  thumb: string
  'medium-square': string
  medium: string
  large: string
}

export interface ResponsiveImages {
  src_set: string
  src: string
  width: number
  height: number
}

export interface Price {
  currency: string
  amount: number
  formatted: string
}

export interface Brand {
  id: number
  name: string
  slug: string
  website?: string
}

export interface MetaField {
  key: string
  value: boolean
}

export interface Taxonomies {
  'food-type': FoodType[]
}

export interface FoodType {
  slug: string
  name: string
  children: null
}

export interface Links {
  first: string
  last: string
  prev: null
  next: null
}

export interface Meta {
  current_page: number
  from: number
  last_page: number
  links: Link[]
  path: string
  per_page: number
  to: number
  total: number
}

export interface Link {
  url: null | string
  label: string
  active: boolean
}
