apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: coder-cert
spec:
  secretName: coder-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: coder.s.4a.software
  dnsNames:
    - coder.s.4a.software
