apiVersion: v1
kind: PersistentVolume
metadata:
  name: coder-volume
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  hostPath:
    path: >-
      /var/lib/rancher/k3s/storage/pvc-coder-volume
    type: DirectoryOrCreate
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem
